apiVersion: apps/v1
kind: Deployment
metadata:
  name: jpotte46-deployment # <--- Rename the deployment
  labels:
    app: myapp # <------------------ Rename the label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-hello-world
  template:
    metadata:
      labels:
        app: springboot-hello-world
    spec:
      serviceAccountName: default
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: devenablement-workshop-pull-secret
      containers:
      - name: springboot-hello-world
        # image will be pulled from localdev Docker Registry if present
        image: registry.ford.com/jpotte46/springboot-hello-world:0.0.1
        ports:
          - containerPort: 8080
            name: http
        env:

        - name: TCP_PORT
          value: "8080"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        resources:
          requests:
            memory: "300Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/v1/hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/hello
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
