apiVersion: v1
kind: Pod
metadata:
  name: glits-pod # <-------- Rename the pod
  labels:
    app: glits-app # <------- Rename the label
spec:
  imagePullSecrets:
  - name: devenablement-workshop-pull-secret
  containers:
  - name: springboot-container
    image: registry.ford.com/jpotte46/springboot-hello-world:0.0.1
    ports:
    - containerPort: 8080
      name: http
    env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    resources:
      requests:
        memory: "300Mi"
        cpu: "100m"
      limits:
        memory: "500Mi"
        cpu: "200m"
