apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lab-route # <------------------- Rename the route
  labels:
    app: lab-app # <-------------------- Rename the label
spec:
  host: lab-app.app.caas.company.com # <--- Rename the host
  port:
    targetPort: 8080
  tls:
    termintaion: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: lab-service # <--- Rename to match your service name
    weight: 100
  wildcardPolicy: None
